[package]
name = "okapi"
description = "Structs for OpenAPI (AKA Swagger) documents"
repository = "https://github.com/GREsau/okapi"
version = "0.5.0-alpha-1"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "openapi", "swagger"]

[features]
derive_json_schema = ["schemars/derive_json_schema"]

[dependencies]
schemars = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[patch.crates-io]
schemars = { git = "https://github.com/raffomania/schemars", branch = "fix-unnecessary-allof" }